USE DATABASE "Digital Marketing Campaign";
USE SCHEMA PUBLIC;

SELECT
    ADVERTISINGPLATFORM,
    COUNT(*) AS total_records,
    AVG(CONVERSION) AS avg_conversion
FROM MARKETING_CAMPAIGNS
GROUP BY ADVERTISINGPLATFORM
ORDER BY avg_conversion DESC;


